# Generated by Django 4.2.7 on 2023-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_alter_dailyrates_currency_pairs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyrates',
            constraint=models.UniqueConstraint(fields=('currency_pairs', 'date'), name='unique_daily_rate'),
        ),
    ]
